### PR TITLE
Add Navbar to the Home Page

### PR DESCRIPTION
**Pull request by Yousuf24100286**
Add navbar to the home page

work need to be done
- decide the background color of the app
- decide menu for the navbar

Currently done
remove the default content provided by next js

### CODE REVIEW

**Comment by rohxama** [comment]
I think black background 20px height ho jaye navbar kee 

orr section 4, 5 ho jaye

**Comment by M0hsinali** [comment]
color of navbar is grey 
size is 30px
2 section

**Comment by Yousuf24100286** [comment]
navbar has been added
is there anything else should I do ??

**Comment by rohxama** [comment]
merge hee kr dein

**Pull request merged**
